# Generated by Django 5.1.6 on 2025-03-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
