# Generated by Django 5.1.6 on 2025-03-05 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_useraccount_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_manager',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
